/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import java.awt.Desktop;
import java.io.File;
/**
 *
 * @author SENA
 */
public class interfazInicio extends javax.swing.JPanel {
    private interfazPrincipal principal;
    
    
    public interfazInicio(interfazPrincipal principal) {
        this.principal = principal;
        initComponents();
    }
    public interfazInicio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnManual = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManual.setBackground(new java.awt.Color(25, 80, 180));
        btnManual.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnManual.setForeground(new java.awt.Color(255, 255, 255));
        btnManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/manual.png"))); // NOI18N
        btnManual.setText("Manual de usuario");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addComponent(btnManual)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(btnManual)
                .addGap(23, 23, 23))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 760, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
         try {
            // Ruta del archivo PDF (relativa o absoluta)
            File archivo = new File("src/Archivos/manual.pdf"); // Cambia la ruta según tu archivo

            // Verificar si Desktop es compatible
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (archivo.exists()) {
                    desktop.open(archivo); // Abre el PDF con el programa predeterminado
                } else {
                    System.out.println("El archivo no se encuentra en la ruta especificada.");
                }
            } else {
                System.out.println("La funcionalidad de abrir archivos no es compatible en este sistema.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnManualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManual;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
